//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CosmosWebForms {
    
    
    public partial class register {
        
        protected System.Web.UI.HtmlControls.HtmlForm RegisterForm;
        
        protected System.Web.UI.WebControls.TextBox First;
        
        protected System.Web.UI.WebControls.TextBox Last;
        
        protected System.Web.UI.WebControls.TextBox Email;
    }
}
